In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
path_5min = "E:/Karan_Bais/python/Ml/Projects/stock/Datasets/Company_datasets/5min"
path_3min = "E:/Karan_Bais/python/Ml/Projects/stock/Datasets/Company_datasets/3min"
path_15min = "E:/Karan_Bais/python/Ml/Projects/stock/Datasets/Company_datasets/15min"
dataset_names = [ "HDFCBANK", "ICICIBANK", "INFY", "RELIANCE", "SBIN", "TCS"]

## read all datasets

In [3]:
datasets_5min = {}
datasets_15min = {}
datasets_3min = {}
for name in dataset_names:
    datasets_5min[name] = pd.read_csv(os.path.join(path_5min, (name+'.csv')))
    datasets_3min[name] = pd.read_csv(os.path.join(path_3min, (name+'.csv')))
    datasets_15min[name] = pd.read_csv(os.path.join(path_15min, (name+'.csv')))

# check for nulls

## 5min

In [12]:
for name,dataset in datasets_5min.items():
    print(name,'\n',dataset.isna().sum(), '\n========================================================================')

HDFCBANK
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
ICICIBANK
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
INFY
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
RELIANCE
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
SBIN
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
TCS
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================

## 3min

In [13]:
for name,dataset in datasets_3min.items():
    print(name,'\n',dataset.isna().sum(), '\n========================================================================')

HDFCBANK
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
ICICIBANK
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
INFY
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
RELIANCE
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
SBIN
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
TCS
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================

## 15min

In [14]:
for name,dataset in datasets_15min.items():
    print(name,'\n',dataset.isna().sum(), '\n========================================================================')

HDFCBANK
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
ICICIBANK
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
INFY
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
RELIANCE
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
SBIN
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================
TCS
 date      0
open      0
high      0
low       0
close     0
volume    0
dtype: int64
========================================================================

# data describe

## 5 min

In [15]:
for name,dataset in datasets_5min.items():
    print(name,'\n',dataset.describe(), '\n========================================================================')

HDFCBANK
                 open           high            low          close  \
count  130860.000000  130860.000000  130860.000000  130860.000000
mean     1012.839709    1013.844663    1011.784442    1012.831343
std       347.216414     347.586301     346.827364     347.215844
min       467.800000     470.500000     464.250000     467.600000
25%       641.850000     642.200000     641.350000     641.837500
50%      1026.750000    1027.775000    1025.400000    1026.750000
75%      1297.750000    1299.000000    1296.150000    1297.662500
max      1718.800000    1724.150000    1707.000000    1720.900000

             volume
count  1.308600e+05
mean   6.910658e+04
std    1.502900e+05
min    0.000000e+00
25%    1.275875e+04
50%    3.139850e+04
75%    7.614925e+04
max    2.179979e+07
========================================================================
ICICIBANK
                 open           high            low          close  \
count  130860.000000  130860.000000  130860.000000  130860.000000
mean      412.274173     412.807386     411.723067     412.271748
std       187.722040     187.904192     187.535908     187.725291
min       164.950000     165.230000     164.320000     165.000000
25%       273.910000     274.180000     273.600000     273.910000
50%       341.300000     342.000000     340.650000     341.300000
75%       532.200000     532.800000     531.600000     532.100000
max       936.000000     936.550000     932.800000     935.450000

             volume
count  1.308600e+05
mean   2.671117e+05
std    4.471214e+05
min    0.000000e+00
25%    9.832600e+04
50%    1.690555e+05
75%    3.073798e+05
max    4.454414e+07
========================================================================
INFY
                 open           high            low          close  \
count  130861.000000  130861.000000  130861.000000  130861.000000
mean      853.628527     854.527337     852.682554     853.623677
std       423.840180     424.264538     423.391783     423.840617
min       432.450000     433.650000     430.080000     432.500000
25%       541.530000     542.130000     541.000000     541.530000
50%       677.380000     678.000000     676.530000     677.380000
75%      1122.850000    1124.150000    1121.400000    1122.750000
max      1953.650000    1953.900000    1951.250000    1953.600000

             volume
count  1.308610e+05
mean   1.102867e+05
std    1.812245e+05
min    0.000000e+00
25%    4.037100e+04
50%    6.599600e+04
75%    1.187710e+05
max    8.422006e+06
========================================================================
RELIANCE
                 open           high            low         close        volume
count  130860.000000  130860.000000  130860.000000  130860.00000  1.308600e+05
mean     1289.889364    1291.331178    1288.345189    1289.86860  1.243181e+05
std       732.549284     733.368619     731.654224     732.53334  1.806120e+05
min       395.000000     395.650000     394.550000     395.00000  0.000000e+00
25%       532.800000     533.300000     532.300000     532.80000  4.272275e+04
50%      1132.425000    1133.650000    1131.100000    1132.35000  7.308650e+04
75%      1999.000000    2001.312500    1996.462500    1999.00000  1.385622e+05
max      2856.150000    2856.150000    2846.850000    2848.90000  7.718411e+06
========================================================================
SBIN
                open           high            low          close        volume
count  130874.00000  130874.000000  130874.000000  130874.000000  1.308740e+05
mean      306.89001     307.299714     306.460144     306.884086  3.680514e+05
std        96.00976      96.102666      95.916497      96.011297  5.422401e+05
min       148.65000     149.150000     148.400000     148.650000  0.000000e+00
25%       250.40000     250.750000     250.050000     250.400000  1.148425e+05
50%       281.85000     282.200000     281.450000     281.800000  2.126565e+05
75%       337.00000     337.400000     336.537500     336.987500  4.205080e+05
max       577.95000     578.500000     577.100000     577.200000  3.137986e+07
========================================================================
TCS
                 open           high            low          close  \
count  130878.000000  130878.000000  130878.000000  130878.000000
mean     2055.743981    2057.772664    2053.580111    2055.721643
std       850.304756     851.068648     849.451829     850.285219
min      1034.000000    1038.000000    1026.000000    1034.000000
25%      1269.700000    1271.000000    1268.500000    1269.707500
50%      1939.075000    1941.500000    1936.600000    1939.000000
75%      2711.575000    2714.000000    2709.000000    2711.537500
max      4041.200000    4042.750000    4036.000000    4040.000000

             volume
count  1.308780e+05
mean   3.740212e+04
std    1.867597e+05
min    0.000000e+00
25%    1.325800e+04
50%    2.242600e+04
75%    4.092175e+04
max    6.373221e+07
========================================================================

## 3 min

In [16]:
for name,dataset in datasets_3min.items():
    print(name,'\n',dataset.describe(), '\n========================================================================')

HDFCBANK
                 open           high            low          close  \
count  236991.000000  236991.000000  236991.000000  236991.000000
mean     1012.661063    1013.432059    1011.849114    1012.655067
std       346.195464     346.474825     345.898481     346.194740
min       466.300000     470.250000     464.250000     466.050000
25%       642.500000     642.950000     642.200000     642.500000
50%      1026.350000    1027.250000    1025.350000    1026.350000
75%      1295.350000    1296.100000    1294.450000    1295.325000
max      1715.800000    1724.150000    1710.000000    1716.650000

             volume
count  2.369910e+05
mean   4.129260e+04
std    9.700099e+04
min    0.000000e+00
25%    7.214000e+03
50%    1.820700e+04
75%    4.445550e+04
max    1.531992e+07
========================================================================
ICICIBANK
                 open           high            low          close  \
count  237138.000000  237138.000000  237138.000000  237138.000000
mean      411.634791     412.040516     411.214694     411.633195
std       186.306946     186.444526     186.164048     186.308246
min       164.770000     165.140000     164.320000     164.860000
25%       274.800000     275.000000     274.550000     274.770000
50%       341.000000     341.500000     340.450000     341.000000
75%       533.400000     533.850000     532.900000     533.400000
max       933.950000     936.550000     933.000000     933.600000

             volume
count  2.371380e+05
mean   1.605137e+05
std    2.812741e+05
min    0.000000e+00
25%    5.566925e+04
50%    9.806050e+04
75%    1.823468e+05
max    2.764202e+07
========================================================================
INFY
                 open           high            low          close  \
count  237094.000000  237094.000000  237094.000000  237094.000000
mean      852.660238     853.346983     851.935802     852.656302
std       424.757628     425.084590     424.407749     424.756640
min       432.650000     433.450000     430.080000     432.650000
25%       540.557500     541.000000     540.100000     540.550000
50%       676.500000     677.150000     675.750000     676.500000
75%      1121.600000    1122.850000    1120.500000    1121.687500
max      1952.950000    1953.900000    1952.100000    1952.700000

             volume
count  2.370940e+05
mean   6.702470e+04
std    1.255618e+05
min    0.000000e+00
25%    2.303300e+04
50%    3.841300e+04
75%    7.068575e+04
max    1.758947e+07
========================================================================
RELIANCE
                 open           high            low          close  \
count  237253.000000  237253.000000  237253.000000  237253.000000
mean     1288.423085    1289.521287    1287.256197    1288.410705
std       729.455913     730.085116     728.778479     729.446792
min       395.000000     395.500000     394.550000     395.000000
25%       532.850000     533.250000     532.450000     532.850000
50%      1139.200000    1140.450000    1137.900000    1139.250000
75%      1992.600000    1994.150000    1990.900000    1992.600000
max      2856.150000    2856.150000    2848.000000    2849.600000

             volume
count  2.372530e+05
mean   7.376914e+04
std    1.137488e+05
min    0.000000e+00
25%    2.420500e+04
50%    4.223700e+04
75%    8.128900e+04
max    7.712778e+06
========================================================================
SBIN
                 open           high            low          close  \
count  236966.000000  236966.000000  236966.000000  236966.000000
mean      306.440635     306.752296     306.112401     306.437003
std        95.003747      95.073165      94.932234      95.003948
min       148.850000     149.150000     148.400000     148.900000
25%       250.650000     250.900000     250.350000     250.650000
50%       282.600000     282.950000     282.300000     282.600000
75%       335.600000     335.950000     335.300000     335.600000
max       577.950000     578.500000     577.100000     577.850000

             volume
count  2.369660e+05
mean   2.196647e+05
std    3.374914e+05
min    0.000000e+00
25%    6.524600e+04
50%    1.235005e+05
75%    2.480870e+05
max    1.930589e+07
========================================================================
TCS
                 open           high            low          close  \
count  237092.000000  237092.000000  237092.000000  237092.000000
mean     2053.187552    2054.740260    2051.539470    2053.173511
std       849.140875     849.734289     848.484856     849.129972
min      1035.380000    1036.030000    1026.000000    1035.380000
25%      1268.280000    1269.200000    1267.480000    1268.250000
50%      1944.100000    1945.800000    1942.250000    1944.075000
75%      2707.837500    2710.112500    2705.412500    2707.875000
max      4041.150000    4042.750000    4036.000000    4041.900000

             volume
count  2.370920e+05
mean   2.261892e+04
std    1.348208e+05
min    0.000000e+00
25%    7.566000e+03
50%    1.306800e+04
75%    2.444625e+04
max    6.242885e+07
========================================================================

## 15 min

In [17]:
for name,dataset in datasets_15min.items():
    print(name,'\n',dataset.describe(), '\n========================================================================')

HDFCBANK
                open          high           low         close        volume
count  43576.000000  43576.000000  43576.000000  43576.000000  4.357600e+04
mean    1013.767666   1015.494416   1011.943194   1013.754356  2.051080e+05
std      347.531815    348.184985    346.839883    347.530808  3.843762e+05
min      470.350000    470.850000    469.150000    470.350000  0.000000e+00
25%      641.787500    642.612500    640.937500    641.787500  4.197050e+04
50%     1026.550000   1028.325000   1024.500000   1026.550000  9.916300e+04
75%     1294.125000   1295.800000   1292.325000   1294.000000  2.352605e+05
max     1711.900000   1724.150000   1701.100000   1711.450000  3.755830e+07
========================================================================
ICICIBANK
                open          high           low         close        volume
count  43575.000000  43575.000000  43575.000000  43575.000000  4.357500e+04
mean     413.511434    414.441456    412.547245    413.505014  7.921998e+05
std      188.002730    188.322731    187.685237    188.014777  1.233488e+06
min      166.320000    167.230000    165.050000    166.140000  0.000000e+00
25%      273.900000    274.350000    273.300000    273.850000  3.210910e+05
50%      343.600000    344.900000    342.450000    343.600000  5.329650e+05
75%      536.000000    536.975000    535.050000    536.000000  9.249275e+05
max      933.550000    936.550000    930.400000    933.350000  1.154300e+08
========================================================================
INFY
                open          high           low         close        volume
count  43576.000000  43576.000000  43576.000000  43576.000000  4.357600e+04
mean     852.420428    853.991035    850.757494    852.407032  3.326465e+05
std      422.122340    422.853154    421.345437    422.116777  4.918645e+05
min      433.480000    434.950000    430.080000    433.480000  0.000000e+00
25%      541.900000    542.750000    540.750000    541.895000  1.334380e+05
50%      675.400000    677.000000    674.225000    675.415000  2.113330e+05
75%     1119.600000   1122.000000   1116.512500   1119.512500  3.664352e+05
max     1952.850000   1953.900000   1948.050000   1951.850000  1.687188e+07
========================================================================
RELIANCE
                open          high           low         close        volume
count  43575.000000  43575.000000  43575.000000  43575.000000  4.357500e+04
mean    1291.812509   1294.347245   1289.077527   1291.754512  3.712958e+05
std      736.770863    738.230726    735.162556    736.721786  4.808639e+05
min      395.000000    396.450000    394.550000    395.000000  5.000000e+01
25%      526.925000    527.575000    526.025000    526.900000  1.415380e+05
50%     1127.950000   1129.850000   1125.350000   1127.850000  2.325400e+05
75%     2002.225000   2006.275000   1997.250000   2001.650000  4.214910e+05
max     2856.150000   2856.150000   2844.750000   2847.900000  1.462987e+07
========================================================================
SBIN
                open          high           low         close        volume
count  43574.000000  43574.000000  43574.000000  43574.000000  4.357400e+04
mean     307.687381    308.399503    306.932725    307.669074  1.089144e+06
std       95.791202     95.956930     95.632864     95.797267  1.452517e+06
min      148.950000    149.650000    148.400000    148.950000  2.200000e+02
25%      249.450000    250.000000    248.800000    249.450000  3.770915e+05
50%      282.500000    283.200000    281.700000    282.500000  6.675730e+05
75%      338.800000    339.650000    337.987500    338.800000  1.263990e+06
max      577.950000    578.500000    576.300000    577.200000  7.017645e+07
========================================================================
TCS
                open          high           low         close        volume
count  43575.000000  43575.000000  43575.000000  43575.000000  4.357500e+04
mean    2056.865381   2060.448677   2053.013366   2056.802134  1.139292e+05
std      849.900382    851.223802    848.399217    849.846400  3.862286e+05
min     1037.530000   1044.180000   1026.000000   1037.530000  0.000000e+00
25%     1269.590000   1271.930000   1267.500000   1269.565000  4.423600e+04
50%     1932.000000   1935.350000   1928.250000   1932.000000  7.217500e+04
75%     2702.325000   2707.175000   2697.525000   2702.400000  1.277765e+05
max     4038.150000   4042.750000   4029.700000   4038.400000  7.460130e+07
========================================================================